package:
  name: mstm_studio
  version: 1.0.1

build:
  number: 1

requirements:
  run:
    - python
about:
  summary: Python wrapper for multiple sphere T-matrix (MSTM) code and Mie theory to calculate surface plasmon resonance (SPR) spectrum and *fit* it to experiment.